# Default values for zenith-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # -- Zenithdb image repository
  repository: zenithdb/zenith
  # -- image pull policy
  pullPolicy: Always
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# -- Specify docker-registry secret names as an array
imagePullSecrets: []

# -- String to partially override zenith-proxy.fullname template (will maintain the release name)
nameOverride: ""
# -- String to fully override zenith-proxy.fullname template
fullnameOverride: ""

# Zenith proxy settings
settings:
  # settings.authEndpoint -- auth endpoint, e.g. "http://console.zenith/authenticate_proxy_request/"
  authEndpoint: ""
  # settings.uri - psql session endpoint, e.g. "http://console.zenith/psql_session/"
  uri: ""

serviceAccount:
  # serviceAccount.create - Specifies whether a service account should be created
  create: true
  # serviceAccount.annotations -- Annotations to add to the service account
  annotations: {}
  # serviceAccount.name - The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Annotations for zenith-proxy pods
podAnnotations: {}

# -- zenith-proxy's pods Security Context
podSecurityContext: {}
  # fsGroup: 2000

# -- zenith-proxy's containers Security Context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  # service.annotations -- Annotations to add to the service
  annotations: {}
  # service.type -- Service type
  type: ClusterIP
  # service.port -- Service management port
  port: 7000

exposedService:
  # exposedService.annotations -- Annotations to add to the exposed service
  annotations: {}
    # service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "4000"
    # external-dns.alpha.kubernetes.io/hostname: chart-example.local
  # exposedService.type -- Exposed service type
  type: LoadBalancer
  # exposedService.port -- Exposed Service proxy port
  port: 5432

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #
  # resources.limits -- The resources limits for the container
  # resources.requests The requested resources for the container
  #
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Node labels for pod assignment.
nodeSelector: {}

# -- Tolerations for pod assignment.
tolerations: []

# -- Affinity for pod assignment
affinity: {}
