{{- if .Values.registerControlPlane.enable -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "neon-storage-controller.fullname" . }}-node-describe
  labels:
    {{- include "neon-storage-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRole
metadata:
  name: {{ include "neon-storage-controller.fullname" . }}-node-reader
  labels:
    {{- include "neon-storage-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "neon-storage-controller.fullname" . }}-node-reader
  labels:
    {{- include "neon-storage-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  {{ include "neon-storage-controller.fullname" . }}-node-reader
subjects:
- kind: ServiceAccount
  name: {{ include "neon-storage-controller.fullname" . }}-node-describe
  namespace: {{ .Release.Namespace }} 
{{- end }}
