apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "neon-storage-controller.fullname" . }}
  labels:
    {{- include "neon-storage-controller.labels" . | nindent 4 }}
spec:
  {{- if .Values.settings.startAsCandidate }}
  # When using RollingUpdate strategy, ensure at least 1 pod is available
  # This works with maxSurge: 1, maxUnavailable: 0 to ensure new pod is created
  # and healthy before the old pod is terminated during node drainage
  minAvailable: 1
  {{- else }}
  # When using Recreate strategy, allow the pod to be disrupted
  # since Recreate doesn't support zero-downtime updates anyway
  maxUnavailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "neon-storage-controller.selectorLabels" . | nindent 6 }}
