{{- if .Values.registerControlPlane.enable -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neon-storage-controller.fullname" . }}-post-install-script
  labels:
    {{- include "neon-storage-controller.labels" . | nindent 4 }}
type: Opaque
data:
  register-storage-controller.py: |-
      {{ tpl (.Files.Get "scripts/register-storage-controller.py") . | b64enc }}
{{- end }}
