apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neon-storage-controller.fullname" . }}-env-vars
  labels:
    {{- include "neon-storage-controller.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.settings.databaseUrl | b64enc | quote }}
  PAGESERVER_JWT_TOKEN: {{ .Values.settings.jwtToken| b64enc | quote }}
