apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neon-storage-controller.fullname" . }}-env-vars
  labels:
    {{- include "neon-storage-controller.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.settings.databaseUrl | b64enc | quote }}
  JWT_TOKEN: {{ .Values.settings.jwtToken| b64enc | quote }}
  CONTROL_PLANE_JWT_TOKEN: {{ .Values.settings.controlPlaneJwtToken | b64enc | quote }}
  CONSOLE_API_KEY: {{ .Values.settings.apiKey | b64enc | quote }}
