apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neon-proxy.fullname" . }}-controlplane-token
  labels:
    {{- include "neon-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  controlplane_token: {{ .Values.settings.controlplane_token | b64enc | quote }}
