apiVersion: v1
kind: Service
metadata:
  name: {{ include "neon-pg-sni-router.fullname" . }}-exposed
  {{- with .Values.exposedService.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  labels:
    {{- include "neon-pg-sni-router.labels" . | nindent 4 }}
spec:
  type: {{ .Values.exposedService.type }}
  ports:
    - port: {{ .Values.exposedService.port }}
      targetPort: router
      protocol: TCP
      name: proxy
  selector:
    {{- include "neon-pg-sni-router.selectorLabels" . | nindent 4 }}
