#!/usr/bin/env python

import os
import json
import logging
import urllib.request
import urllib.error

# region_id different in console/cplan with prefix aws-<region>
REGION = os.environ["REGION_ID"]
# ZONE env will be autogenerated from init container
ZONE = os.environ["ZONE"]
HOST = os.environ["HOST"]
PORT = os.getenv("PORT", 80)

CPLANE_JWT_TOKEN = os.environ["CONTROL_PLANE_JWT_TOKEN"]

# To register new pageservers
URL_PATH = "management/api/v2/pageservers"
# To get pageservers
ADMIN_URL_PATH = f"regions/{REGION}/api/v1/admin/pageservers"

CPLANE_MANAGEMENT_URL = f"{os.environ['CPLANE_URL'].strip('/')}/{URL_PATH}"
CONSOLE_URL = f"{os.environ['CONSOLE_URL']}/{ADMIN_URL_PATH}"

PAYLOAD = dict(
    host=HOST,
    region_id=REGION,
    port=6400,
    disk_size=0,
    instance_id=HOST,
    http_host=HOST,
    http_port=int(PORT),
    availability_zone_id=ZONE,
    instance_type="",
    register_reason="Storage Controller Virtual Pageserver",
    active=True,
    is_storage_controller=True,
    # Hardcoded because nothing is checking this version.
    version=0,
)


def get_data(url, token, host=None, method="GET", data=None, raise_on_error=True):
    if host is not None:
        url = f"{url}/{host}"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/json",
        "Content-Type": "application/json",
    }
    # Check if the server is already registered
    req = urllib.request.Request(url=url, headers=headers, method=method, data=data)
    try:
        with urllib.request.urlopen(req) as response:
            code = response.getcode()
            response_body = response.read()
    except urllib.error.HTTPError as e:
        code = e.code
        response_body = e.read()

    if code == 200:
        return json.loads(response_body)

    if raise_on_error:
        raise Exception(f'{method} {url} returned unexpected response: {code} {response_body}')

    return {}


def get_pageserver_id(url, token):
    data = get_data(url, token, HOST, raise_on_error=False)
    if "node_id" in data:
        return int(data["node_id"])


def register(url, token, payload):
    data = str(json.dumps(payload)).encode()
    response = get_data(url, token, data=data, method="POST")
    log.info(response)
    if "node_id" in response:
        return int(response["node_id"])


if __name__ == "__main__":
    logging.basicConfig(
        style="{",
        format="{asctime} {levelname:8} {name}:{lineno} {message}",
        level=logging.INFO,
    )

    log = logging.getLogger()

    log.info(
        json.dumps(
            dict(
                CPLANE_MANAGEMENT_URL=CPLANE_MANAGEMENT_URL,
                CONSOLE_URL=CONSOLE_URL,
                **PAYLOAD,
            ),
            indent=4,
        )
    )

    log.info("check if pageserver already registered")
    node_id = get_pageserver_id(
        CPLANE_MANAGEMENT_URL, CPLANE_JWT_TOKEN
    )

    if node_id is None:
        log.info("Registering storage controller")
        node_id = register(
            CPLANE_MANAGEMENT_URL, CPLANE_JWT_TOKEN, PAYLOAD
        )
        log.info(
            f"Storage controller registered with node_id {node_id}"
        )
    else:
        log.info(
            f"Storage controller already registered with node_id {node_id}"
        )
