apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aws-cost-reporter.fullname" . }}
  labels:
    {{- include "aws-cost-reporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  slackToken: {{ .Values.slack.token | quote }}
  {{- with .Values.aws }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
