apiVersion: v1
kind: Service
metadata:
  name: {{ include "zenith-proxy.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  labels:
    {{- include "zenith-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mgmt
      protocol: TCP
      name: mgmt
  selector:
    {{- include "zenith-proxy.selectorLabels" . | nindent 4 }}
