apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "neon-broker.fullname" . }}
  labels:
    {{- include "neon-broker.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  # Which pods the Deployment is managing (duplicates template.metadata.labels).
  selector:
    matchLabels:
      {{- include "neon-broker.selectorLabels" . | nindent 6 }}
  # Pod template.
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # Labels set on created pods.
      labels:
        {{- include "neon-broker.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "neon-broker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: sysctl
        image: busybox:1.35.0
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        args:
        - /bin/sh
        - -c
        - 'sysctl -w net.ipv4.tcp_keepalive_time=60; sysctl -w net.ipv4.tcp_keepalive_intvl=30'
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - neon_broker
            - --listen-addr
            # In the container, use the same port as service.
            - 0.0.0.0:{{ .Values.service.port }}
          ports:
            - name: broker
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /metrics
              port: broker
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /metrics
              port: broker
            periodSeconds: 15
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: broker
            periodSeconds: 15
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
