{{- if eq .Values.settings.pemfile "/certs/dummy.pem" }}
{{/*  this is a dummy certificate secret to make tests pass */}}
apiVersion: v1
kind: Secret
metadata:
  name: neon-endpoint-storage-cert
type: kubernetes.io/tls
data:
  pemfile.pem: >-
    LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUNvd0JRWURLMlZ3QXlFQTNMdnFsclcxanp6c3lO
    U2pCUVdxdmhRSkFJL2hYWmI4YjQ1YXZhZUdGd0E9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
{{- end }}
