{{- if eq .Values.settings.pemfile "/certs/dummy.pem" }}
{{/*  this is a dummy certificate secret to make tests pass */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neon-endpoint-storage.fullname" . }}-cert
type: Opaque
data:
  pemfile.pem: >-
    LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUNvd0JRWURLMlZ3QXlFQTNMdnFsclcxanp6c3lOU2pCUVdxdmhRSkFJL2hYWmI4YjQ1YXZhZUdGd0E9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
{{- end }}
