apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neon-storage-scrubber.fullname" . }}-env-vars
  labels:
    {{- include "neon-storage-scrubber.labels" . | nindent 4 }}
type: Opaque
data:
  STORAGE_CONTROLLER_JWT_TOKEN: {{ .Values.storageScrubber.storageControllerJwtToken | b64enc | quote }}
