{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "neon-storage-scrubber.serviceAccountName" . }}
  labels:
    {{- include "neon-storage-scrubber.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
